
name: Terraform Destroy on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  destroy-infra:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    # Only run if PR WAS NOT MERGED
    if: github.event.pull_request.merged == false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform Init
      run: terraform init -input=false
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
